apiVersion: v1
kind: ConfigMap
metadata:
  name: xuanwu-mall-configmap
  namespace: xuanwu-system
data:
  config.yaml: |
    xuanwu:
      mall:
        frontend:
          enabled: true
    spring:
      datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://mysql.iam-system:3306/wecoding_mall_1?createDatabaseIfNotExist=true&autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false
        username: root
        password: WeCoding@2023
      jpa:
        database-platform: org.hibernate.dialect.MySQLDialect