apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
  name: xuanwu-codegen
  namespace: xuanwu-system
spec:
  ingressClassName: traefik
  rules:
    - host: codegen.wecoding.top
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: xuanwu-codegen-service
                port:
                  number: 9030
