server:
  port: 9040
  servlet:
    context-path: /
  shutdown: graceful
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,application/javascript,application/json,image/svg+xml
    min-response-size: 1024
  # undertow
  undertow:
    threads:
      io: 32
      worker: 256
    buffer-size: 1024

spring:
  application:
    name: @artifactId@
  ai:
    openai:
      api-key: sk-xxxxxx
      base-url: https://api.openai-proxy.org
