name: "xuanwu-codegen"
serviceType: "deployment"
containers:
  - name: "codegen"
    hub: null
    dev:
      gitUrl: ""
      image: "devops-wecoding-docker.pkg.coding.net/wecoding/public/nocalhost-dev-java:21"
      shell: "zsh"
      workDir: "/xuanwu"
      storageClass: ""
      resources: null
      persistentVolumeDirs: [ ]
      command:
        run:
          - "java"
          - "-jar"
          - "-Dspring.config.additional-location=/xuanwu/config.yaml"
          - "xuanwu-codegen/target/xuanwu-codegen-*.jar"
        debug:
          - "java"
          - "-Xdebug"
          - "-Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=5005"
          - "-Dspring.config.additional-location=/xuanwu/config.yaml"
          - "-jar"
          - "xuanwu-codegen/target/xuanwu-codegen-*.jar"
      debug:
        remoteDebugPort: 5005
        language: "java"
      hotReload: false
      sync:
        mode: "pattern"
        filePattern:
          - "xuanwu-codegen/target/xuanwu-codegen-*.jar"
        ignoreFilePattern: [ ]
      env: [ ]
      portForward: [ ]
