server:
  port: 9090
  servlet:
    context-path: /

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:D:\XuanwuMall\data\mall_db
    username: xuanwu
    password: WeCoding@319
  jpa:
    generate-ddl: true
    show-sql: true
