server:
  port: 9090
  servlet:
    context-path: /
  shutdown: graceful
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,application/javascript,application/json,image/svg+xml
    min-response-size: 1024
  # undertow
  undertow:
    threads:
      io: 32
      worker: 256
    buffer-size: 1024

spring:
  application:
    name: @artifactId@
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
  main:
    allow-bean-definition-overriding: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  h2:
    console:
      enabled: true
      path: /h2-console
  #    driver-class-name: org.h2.Driver
  #    url: jdbc:h2:file:D:/WorkSpace/WeCoding/Xuanwu/_output/db/xuanwu_mall
  #    username: xuanwu
  #    password: WeCoding@319
  jpa:
    generate-ddl: true
    show-sql: true
  profiles:
    active: dev

logging:
  config: classpath:logback-spring.xml
  level:
    top.wecoding.xuanwu: debug
    org.springframework: warn

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wecoding_mall?createDatabaseIfNotExist=true&autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false
    username: root
    password: 123456
  jpa:
    database: mysql
