server:
  port: 9090
  servlet:
    context-path: /
  shutdown: graceful
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,application/javascript,application/json,image/svg+xml
    min-response-size: 1024
  # undertow
  undertow:
    threads:
      io: 32
      worker: 256
    buffer-size: 1024

spring:
  application:
    name: @artifactId@
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
  main:
    allow-bean-definition-overriding: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    generate-ddl: true
    show-sql: false

logging:
  config: classpath:logback-spring.xml
  level:
    top.wecoding.xuanwu: debug
    org.springframework: warn

xuanwu:
  printer:
    kitchen-template: classpath:/templates/default_kitchen.json
    demo-order: classpath:/templates/demo_order.json

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wecoding_mall?createDatabaseIfNotExist=true&autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false
    username: root
    password: 123456
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
